version: "3.9"
services:
  prisma-mariadb-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}